all: spacecraft ground_station

spacecraft: spacecraft/spacecraft.c
	gcc -o spacecraft/spacecraft spacecraft/spacecraft.c

ground_station: ground_station/ground_station.c
	gcc -o ground_station/ground_station ground_station/ground_station.c